<?php
/**
 * @var $block Swish\Referral\Block\Customer\Account\Content;
 */
?>
<div data-bind="scope: 'referral-content'" class="referral container">
    <div class="loader" data-bind="visible: !visible()">
        <img alt='loader' src="<?= $this->getViewFileUrl('Swish_Referral::images/loader.gif'); ?>"/>
    </div>
    <div data-mage-init='<?= $block->getComponent('referral-content') ?>'>
        <div>
            <div>
                <label for="referral_code"><?= $block->escapeHtml(__('Your referral code')) ?></label>
                <input name="referral_code" id="referral_code"
                       type="text"
                       data-bind="value: getCode(), textInput: referralCode"/>
                <div class="validate">
                    <img alt='success'
                         src="<?= $this->getViewFileUrl('Swish_Referral::images/checked.svg'); ?>"
                         data-bind="visible: (isValid() === true)" style="display: none"/>
                    <img alt='error'
                         src="<?= $this->getViewFileUrl('Swish_Referral::images/cancel.svg'); ?>"
                         data-bind="visible: (isValid() === false)" style="display: none"/>
                </div>
            </div>
            <div class="actions">
                <button class="apply" type="button" data-bind="visible: (showApply && isValid), click: apply" style="display: none;">
                    <?= $block->escapeHtml(__('Apply')) ?>
                </button>
                <button type="button" data-bind="click: generate">
                    <?= $block->escapeHtml(__('Generate')) ?>
                </button>
            </div>
        </div>
    </div>
    <div class="list">
        <div class="container">
            <div class="header">
                <span><?= $block->escapeHtml(__('Referrals')) ?></span>
                <div class="reload">
                    <img alt='loader' src="<?= $this->getViewFileUrl('Swish_Referral::images/reload.svg'); ?>"/>
                </div>
            </div>
            <div class="table">
                <table>
                    <tr>
                        <th><?= $block->escapeHtml(__('Name'))?></th>
                        <th><?= $block->escapeHtml(__('Reward'))?></th>
                        <th><?= $block->escapeHtml(__('Actions'))?></th>
                    </tr>
                    <tr>
                        <td>Customer 1</td>
                        <td>30$</td>
                        <td>
                            <div class="remove">
                                <img alt='loader' src="<?= $this->getViewFileUrl('Swish_Referral::images/remove.svg'); ?>"/>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>Customer 2</td>
                        <td>20$</td>
                        <td>
                            <div class="remove">
                                <img alt='loader' src="<?= $this->getViewFileUrl('Swish_Referral::images/remove.svg'); ?>"/>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>